// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL01DkaaqFFajBR8B-UYzd4kZt4j7Hp1c',
    appId: '1:189450126776:web:c169b1012b96b5bfe57b4d',
    messagingSenderId: '189450126776',
    projectId: 'chatapp-7d944',
    authDomain: 'chatapp-7d944.firebaseapp.com',
    storageBucket: 'chatapp-7d944.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHcq0lmWCmozGlxKtK4_OnjikuT1dJlhQ',
    appId: '1:189450126776:android:22bce00818445f23e57b4d',
    messagingSenderId: '189450126776',
    projectId: 'chatapp-7d944',
    storageBucket: 'chatapp-7d944.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQP1C5cjVdpUOusMokt4o11JX8eBfzSwA',
    appId: '1:189450126776:ios:bf0efa550b84eaa7e57b4d',
    messagingSenderId: '189450126776',
    projectId: 'chatapp-7d944',
    storageBucket: 'chatapp-7d944.appspot.com',
    iosBundleId: 'com.example.chatAppUsingFlutterAndFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQP1C5cjVdpUOusMokt4o11JX8eBfzSwA',
    appId: '1:189450126776:ios:717b30281ecf977ee57b4d',
    messagingSenderId: '189450126776',
    projectId: 'chatapp-7d944',
    storageBucket: 'chatapp-7d944.appspot.com',
    iosBundleId: 'com.example.chatAppUsingFlutterAndFirebase.RunnerTests',
  );
}
